---
language: ruby
rvm:
  - 3.1

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      name: "version"
      script: ruby -e "require './lib/qat/reporter/xray/version'; raise StandardError.new unless Gem::Specification::load('qat-reporter-xray-standalone.gemspec').version.to_s == QAT::Reporter::Xray::VERSION"
      if: tag IS blank

    - name: "gem build"
      script: gem build *.gemspec
      if: tag IS blank

    - stage: release
      name: "gem release"
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        gemspec: qat-reporter-xray-standalone.gemspec